### ISSUE TITLE
Upload any Web based Project

### ISSUE THREAD

**Issue by diwakar1593** [diwakar1593/Web-Project#1]

**Comment by krrishexe** [comment]
Hey , it can be any web project ?
like a weather app too ?

**Comment by diwakar1593** [comment]
@krrishexe yes

**Comment by Devrishi-Dutta** [comment]
Can I make a pr after 5th October so that it is counted for hacktoberfest?

**Comment by ghost** [comment]
Can i make a image background remover website using APIs?
Please assign to me

**Comment by diwakar1593** [comment]
@Igdtuwresource Assigned! You can Add

**Comment by ghost** [comment]
I have created the pull request. I hope it gets merged.

**Comment by krrishexe** [comment]
hey @diwakar1593 i have also added a project and created a pull request , kindly merger it. 
Many Thanks

**Comment by harshmishra19** [comment]
@diwakar1593 Can you plz assign me this issue

**Comment by Aditi-K4** [comment]
@diwakar1593 Hello! I'm interested in taking on the task of adding an Online Dynamic Resume/CV using HTML, CSS, JavaScript, and APIs. Could you please consider assigning me this issue?

**Comment by diwakar1593** [comment]
@Aditi-K4 Assigned!

**Comment by sharadj34** [comment]
Hey! @diwakar1593 Can I add a Blog Website with a theme of macOS and cmd. 
Could you please consider assigning me this issue?
